Get-ChildItem images | Where-Object { $_.Name -match "^1[^0-9]" } | Rename-Item -NewName "volgograd.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^2[^0-9]" } | Rename-Item -NewName "volzhsky.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^3[^0-9]" } | Rename-Item -NewName "kamyshin.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^4[^0-9]" } | Rename-Item -NewName "mikhaylovka.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^5[^0-9]" } | Rename-Item -NewName "uryupinsk.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^6[^0-9]" } | Rename-Item -NewName "frolovo.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^7[^0-9]" } | Rename-Item -NewName "kalach.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^8[^0-9]" } | Rename-Item -NewName "kotelnikovo.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^9[^0-9]" } | Rename-Item -NewName "kotovo.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^10" } | Rename-Item -NewName "surovikino.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^11" } | Rename-Item -NewName "krasnoslobodsk.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^12" } | Rename-Item -NewName "zhirnovsk.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^13" } | Rename-Item -NewName "novoanninsky.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^14" } | Rename-Item -NewName "pallasovka.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^15" } | Rename-Item -NewName "dubovka.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^16" } | Rename-Item -NewName "nikolaevsk.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^17" } | Rename-Item -NewName "leninsk.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^18" } | Rename-Item -NewName "petrov_val.jpg" -ErrorAction SilentlyContinue
Get-ChildItem images | Where-Object { $_.Name -match "^19" } | Rename-Item -NewName "serafimovich.jpg" -ErrorAction SilentlyContinue
